bolt:
  db:
    path: .local/test.db

server:
  bind_ip: 127.0.0.1
  http_listen_port: 18000
  grpc_listen_port: 19000

lifecycler:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
#    heartbeat_timeout: 700ms
#    zone_awareness_enabled: false
#    excluded_zones: ''
#  num_tokens: 3
#  heartbeat_period: 1s
#  heartbeat_timeout: 700ms
#  observe_period: 1s
#  join_after: 1s
#  min_ready_duration: 2s
#  interface_names: [ ]
#  final_sleep: 2s
#  tokens_file_path: .local/tokens
#  availability_zone: ''
#  unregister_on_shutdown: true
#  readiness_check_ring_health: false