apiVersion: v1
kind: Service
metadata:
  name: memberlist
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: simple-replica
  publishNotReadyAddresses: true

---

apiVersion: v1
kind: Service
metadata:
  name: simple-replica
spec:
  selector:
    app.kubernetes.io/name: simple-replica
  ports:
    - port: 80
      targetPort: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-replica
  labels:
    app.kubernetes.io/name: simple-replica
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-replica
  replicas: 3
  template:
    metadata:
      name: simple-replica
      labels:
        app.kubernetes.io/name: simple-replica
    spec:
      containers:
        - name: simple-replica
          image: kwseo.io/simple-replica:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 7946
              name: memberlist
          readinessProbe:
            httpGet:
              port: http
              path: /ready
