apiVersion: v1
kind: Service
metadata:
  name: memberlist
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: simple-replica
  publishNotReadyAddresses: true

---

apiVersion: v1
kind: Service
metadata:
  name: simple-replica
spec:
  selector:
    app.kubernetes.io/name: simple-replica
  ports:
    - port: 80
      targetPort: http